/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ApiPublicPrintifyProductsRouteImport } from './routes/api.public.printify-products'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrintifyProductsRoute =
  ApiPublicPrintifyProductsRouteImport.update({
    id: '/api/public/printify-products',
    path: '/api/public/printify-products',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/public/printify-products': typeof ApiPublicPrintifyProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/public/printify-products': typeof ApiPublicPrintifyProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/public/printify-products': typeof ApiPublicPrintifyProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/success'
    | '/products/$productId'
    | '/api/public/printify-products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/success'
    | '/products/$productId'
    | '/api/public/printify-products'
  id:
    | '__root__'
    | '/'
    | '/success'
    | '/products/$productId'
    | '/api/public/printify-products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuccessRoute: typeof SuccessRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ApiPublicPrintifyProductsRoute: typeof ApiPublicPrintifyProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/printify-products': {
      id: '/api/public/printify-products'
      path: '/api/public/printify-products'
      fullPath: '/api/public/printify-products'
      preLoaderRoute: typeof ApiPublicPrintifyProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuccessRoute: SuccessRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ApiPublicPrintifyProductsRoute: ApiPublicPrintifyProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
